Updated shutdown-helper script to work in tandem with eject, thanks Alexander

diff --git a/trunk/scripts/shutdown-helper b/trunk/scripts/shutdown-helper
--- a/trunk/scripts/shutdown-helper
+++ b/trunk/scripts/shutdown-helper
@@ -1,34 +1,72 @@
 #!/bin/sh
 
+FILES="/lib/libc.so.6
+/lib/ld-linux.so.2
+/lib/libreadline.so.5.0
+/lib/libhistory.so.5.0
+/lib/libncurses.so.5
+/lib/libdl.so.2
+/lib/libblkid.so.1
+/lib/libuuid.so.1
+/bin/sh
+/bin/umount
+/sbin/losetup
+/sbin/halt
+/sbin/reboot
+/usr/sbin/chroot
+/usr/bin/eject
+/bin/sleep
+/lib/libm.so.6
+/lib/librt.so.1
+/lib/libpthread.so.0
+/dev/console
+/dev/null
+/dev/lfs-cd
+/dev/loop0"
+
 case "$RUNLEVEL" in
 	0)
-		HALTOPT=-p
+		HALT="/sbin/halt -d -f -i -p"
 		;;
 	6)
-		HALTOPT=-r
+		HALT="/sbin/reboot -d -f -i"
 		;;
 esac
-cp -a /usr/lib/klibc/bin /dev/shm
-cp -a /usr/lib/klibc/lib /dev/shm
-mkdir /dev/shm/dev
-mkdir /dev/shm/old
-cp -a /dev/console /dev/loop0 /dev/null /dev/shm/dev
-mkdir /dev/shm/sbin
+mkdir /dev/shm/old /dev/shm/proc /dev/shm/etc
+ln -s /proc/mounts /dev/shm/etc/mtab
+echo "$FILES" | cpio -pLd --quiet /dev/shm
 cat >/dev/shm/sbin/init <<EOF
 #!/bin/sh
+
+fail() {
+	echo "Could not unmount the CD, sorry. Please report this as a bug."
+	sleep 5
+	$HALT
+	while true ; do sleep 1 ; done
+}
+
 exec </dev/console >/dev/console 2>/dev/console
-while ! umount /old 2>/dev/null ; do sleep 1 ; done
-umount /.sqfs
-losetup -d /dev/loop0
-umount /.cdrom
-echo -n "Remove the CD from the drive and press Enter..."
+TIMEOUT=
+while ! umount -n /old 2>/dev/null && [ "$TIMEOUT" != "....." ] ; do
+        sleep 1
+	TIMEOUT=".$TIMEOUT"
+done
+[ "$TIMEOUT" = "....." ] && fail
+umount -n /.sqfs || fail
+losetup -d /dev/loop0 || fail
+umount -n /.cdrom || fail
+( sleep 30 ; $HALT ) &
+eject -r /dev/lfs-cd
+echo -n "Take the CD, close the CD-ROM tray and press Enter..."
 read ENTER
-halt $HALTOPT
+$HALT
+while true ; do sleep 1 ; done
 EOF
 chmod 755 /dev/shm/sbin/init
 ln -nsf /old/dev/initctl /dev/shm/dev/initctl
 umount /tmp
 umount -a -t nounionfs
 cd /dev/shm
+mount -n -t proc proc /dev/shm/proc
 pivot_root . old
-exec chroot . /old/lib/ld-linux.so.2 --library-path /old/lib /old/sbin/init u
+exec chroot . /old/sbin/init u
