Updated version in documentation Fixed error reporting in shutdown helper

diff --git a/trunk/scripts/shutdown-helper b/trunk/scripts/shutdown-helper
--- a/trunk/scripts/shutdown-helper
+++ b/trunk/scripts/shutdown-helper
@@ -38,29 +38,32 @@ echo "$FILES" | cpio -pLd --quiet /dev/shm
 cat >/dev/shm/sbin/init <<EOF
 #!/bin/sh
 
-fail() {
-	echo "Could not unmount the CD, sorry. Please report this as a bug."
-	sleep 5
+halt() {
 	$HALT
 	while true ; do sleep 1 ; done
 }
 
+fail() {
+	echo "Could not unmount the CD, sorry. Please report this as a bug."
+	sleep 5
+	halt
+}
+
 exec </dev/console >/dev/console 2>/dev/console
 TIMEOUT=
-while ! umount -n /old 2>/dev/null && [ "$TIMEOUT" != "....." ] ; do
+while ! umount -n /old 2>/dev/null && [ "\$TIMEOUT" != "....." ] ; do
         sleep 1
-	TIMEOUT=".$TIMEOUT"
+	TIMEOUT=".\$TIMEOUT"
 done
-[ "$TIMEOUT" = "....." ] && fail
+[ "\$TIMEOUT" = "....." ] && fail
 umount -n /.sqfs || fail
 losetup -d /dev/loop0 || fail
 umount -n /.cdrom || fail
-( sleep 30 ; $HALT ) &
 eject -r /dev/lfs-cd
 echo -n "Take the CD, close the CD-ROM tray and press Enter..."
+( sleep 30 ; halt ) &
 read ENTER
-$HALT
-while true ; do sleep 1 ; done
+halt
 EOF
 chmod 755 /dev/shm/sbin/init
 ln -nsf /old/dev/initctl /dev/shm/dev/initctl
