Removed verbose tag from tar call in unpack script

diff --git a/trunk/scripts/unpack b/trunk/scripts/unpack
--- a/trunk/scripts/unpack
+++ b/trunk/scripts/unpack
@@ -13,11 +13,11 @@ if [ ! -f $1 ] ; then
 fi
 
 if echo $1 | grep -q "tar.gz" || echo $1 | grep -q ".tgz" ; then
-	$TAR -xzvf $1 || echo "Error: Unpacking of \"$1\" failed."
+	$TAR -xzf $1 || echo "Error: Unpacking of \"$1\" failed."
 elif echo $1 | grep -q "tar.bz2" ; then
-	$TAR -xjvf $1 || echo "Error: Unpacking of \"$1\" failed."
+	$TAR -xjf $1 || echo "Error: Unpacking of \"$1\" failed."
 elif [ `expr "$1" : '.*\(...\)'` = "tar" ] ; then
-	$TAR -xvf $1 || echo "Error: Unpacking of \"$1\" failed."
+	$TAR -xf $1 || echo "Error: Unpacking of \"$1\" failed."
 else
 	echo "Error: Bad format or unknown compression type"
 fi	
